# Use a Python base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy only the necessary files and built artifacts from the builder stage
COPY requirements.txt .
COPY app.py .
COPY tc04.pkl .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application when the container starts
CMD ["python", "app.py"]