# Imagem base Python
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copia os arquivos necessários
COPY requirements.txt .
COPY app.py .
COPY tc04.pkl .

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expõe a porta
EXPOSE 5000

# Execute app quando o container inicia
CMD ["python", "app.py"]