# Stage 1: Build the application using the devel image
# This stage has all necessary headers and compilers
FROM nvidia/cuda:13.0.1-base-ubuntu24.04 AS base

WORKDIR /app

# Install necessary system dependencies
RUN apt-get update && apt-get install -y python3 python3-pip build-essential python3-venv

RUN python3 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
ENV XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/cuda/

# Copy only the necessary files and built artifacts from the builder stage
COPY requirements.txt .
COPY app.py .
COPY tc04.pkl .

# Install Python dependencies (assuming a requirements.txt file)
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 5000

CMD ["python3", "./app.py"]
